version: '3'

services:
  nginx:
    image: nginx:1.19-alpine
    container_name: nginx
    ports:
      - "80:80"
    networks:
      node:
        aliases:
          - node.test
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - node

  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    container_name: node
    user: node
    environment:
      NODE_ENV: development
    volumes:
      - ./:/home/node/app
    networks:
      - node
    ports:
      - "3000:3000"

networks:
    node: